plt.figure(figsize=(10, 6))
sns.boxplot(x='Type_of_Renewable_Energy', y='Storage_Efficiency_Percentage', data=df, palette='viridis')
plt.title('Storage Efficiency of Different Types of Renewable Energy')
plt.xlabel('Type of Renewable Energy')
plt.ylabel('Storage Efficiency (%)')
plt.xticks(ticks=[0, 1, 2, 3, 4, 5, 6], labels=['Solar', 'Wind', 'Hydroelectric', 'Geothermal', 'Biomass', 'Tidal', 'Wave'])
plt.show()
